//import './AlertMessage.story'
//import './DrawerButton.story'
//import './FullButton.story'
//import './RoundedButton.story'
import './TextInputWithLabel/TextInputWithLabel.story'
import './Button/MyButton.story'
import './Picker/MyPicker.story'
